(defun is-square? (n)
  ( write n)
  (terpri)
  ( write (expt (- n 1) 2))
  (terpri)
  ( write (= (expt (- n 1) 2) n))
   (terpri)
  (cond
;;     ((= (expt n 2) 16) "hello")
    ((< n 0) nil)
    ((= n 0) nil)
    ((= (expt (- n 1) 2) n) t)
    ( (is-square? (- n 1) ))
  )
)